# On and Off Statistics

In [10]:
# Let's first load all required packages...
import os
import pandas as pd
import numpy  as np
import dtale

from config import *
from bball_stats import *
import tools

In [2]:
# game_id = 2031329     # Besson issue with subing and non-matching points

game_id = 1976463   # game with no "bugs" in subs

Process game and extract all data structures (e.g., play-by-plays, stints):

In [3]:
set_logging("INFO")

game_json = tools.get_json_data(game_id)
starters = get_starters(game_json, 1)
pbp_df = get_pbp_df(game_json)
stints = pbp_stints_extract(pbp_df, starters, 1)

result = build_game_stints_stats_df(game_id)
stats_df = result['stint_stats_df']
pbp_df = result['pbp_df']
team1 = result['teams'][0]
team2 = result['teams'][1]
stints1_df = result['stints_df'].query('tno == 1')
stints2_df = result['stints_df'].query('tno == 2')

stints1_df[['id', 'lineup']].to_records(index=False)

rec.array([( 1, list(['C. Agada', 'C. Goulding', 'D. Barlow', 'J. Lual-Acuil', 'M. Dellavedova'])),
           ( 2, list(['A. Hukporti', 'B. Newley', 'C. Agada', 'M. Peatling', 'S. Ili'])),
           ( 3, list(['A. Hukporti', 'B. Newley', 'J. White', 'M. Peatling', 'S. Ili'])),
           ( 4, list(['C. Goulding', 'D. Barlow', 'J. Lual-Acuil', 'J. White', 'S. Ili'])),
           ( 5, list(['C. Goulding', 'J. Lual-Acuil', 'J. White', 'M. Dellavedova', 'M. Peatling'])),
           ( 6, list(['A. Hukporti', 'C. Goulding', 'J. White', 'M. Dellavedova', 'M. Peatling'])),
           ( 7, list(['A. Hukporti', 'C. Agada', 'C. Goulding', 'M. Dellavedova', 'M. Peatling'])),
           ( 8, list(['A. Hukporti', 'C. Agada', 'C. Goulding', 'J. White', 'M. Dellavedova'])),
           ( 9, list(['C. Agada', 'C. Goulding', 'J. Lual-Acuil', 'J. White', 'M. Dellavedova'])),
           (10, list(['B. Newley', 'C. Goulding', 'J. Lual-Acuil', 'M. Peatling', 'S. Ili'])),
           (11, list(['B. Newley', 'C. Agada', 'J. Lual-Acuil', 'M. Peatling', 'S. Ili'])),
           (12, list(['B. Newley', 'C. Agada', 'D. Barlow', 'M. Peatling', 'S. Ili'])),
           (13, list(['A. Hukporti', 'C. Goulding', 'D. Barlow', 'M. Dellavedova', 'S. Ili'])),
           (14, list(['C. Agada', 'D. Okwera', 'D. Prewster', 'J. Lual-Acuil', 'J. White'])),
           (15, list(['C. Agada', 'C. Dalton', 'D. Okwera', 'D. Prewster', 'J. White']))],
          dtype=[('id', '<i8'), ('lineup', 'O')])

In [4]:
dtale.show(stints1_df)

Check if there are plays with no player assigned.

In principle, there should be none, but there are usually some, e.g., in rebounds; guess it's bc they missed the relevant player in the play?

In [5]:
# find plays with no player assigned! Should be empty 
pbp_df.query('player == "nan. nan" and ((tno == 1) or (tno == 2))')

,team_name,team_short_name,clock,s1,s2,lead,tno,period,periodType,pno,player,success,actionType,actionNumber,previousAction,qualifier,subType,scoring,stint1,stint2
507,New Zealand Breakers,Breakers,00:09:09,0,0,0,2,1,REGULAR,0,nan. nan,1,rebound,19,17,[team],offensive,0,1,1
478,New Zealand Breakers,Breakers,00:06:16,12,4,8,2,1,REGULAR,0,nan. nan,1,timeout,58,,[],full,0,1,1
452,Melbourne United,United,00:03:44,14,10,4,1,1,REGULAR,0,nan. nan,1,timeout,87,,[],full,0,1,1
427,Melbourne United,United,00:02:21,18,12,6,1,1,REGULAR,0,nan. nan,1,jumpball,120,,[],heldball,0,3,2
420,Melbourne United,United,00:02:08,18,12,6,1,1,REGULAR,0,nan. nan,1,rebound,129,127,[team],offensive,0,3,3
401,New Zealand Breakers,Breakers,00:00:30.100000,21,14,7,2,1,REGULAR,0,nan. nan,1,turnover,156,,[team],8sec,0,3,3
303,New Zealand Breakers,Breakers,00:03:33,27,21,6,2,2,REGULAR,0,nan. nan,1,timeout,282,,[],full,0,1,8
298,New Zealand Breakers,Breakers,00:03:09,27,22,5,2,2,REGULAR,0,nan. nan,1,rebound,289,288,[],offensivedeadball,0,1,8
293,New Zealand Breakers,Breakers,00:02:55,27,23,4,2,2,REGULAR,0,nan. nan,1,rebound,296,294,[team],defensive,0,1,9
282,New Zealand Breakers,Breakers,00:01:35,27,25,2,2,2,REGULAR,0,nan. nan,1,rebound,311,310,[],offensivedeadball,0,1,9
225,New Zealand Breakers,Breakers,00:06:37,44,33,11,2,3,REGULAR,0,nan. nan,1,timeout,389,,[],full,0,9,10
220,New Zealand Breakers,Breakers,00:05:47,44,35,9,2,3,REGULAR,0,nan. nan,1,rebound,396,395,[team],defensive,0,9,11
173,New Zealand Breakers,Breakers,00:01:29,52,42,10,2,3,REGULAR,0,nan. nan,1,rebound,459,458,[team],offensive,0,11,13
169,New Zealand Breakers,Breakers,00:01:16,52,42,10,2,3,REGULAR,0,nan. nan,1,rebound,465,463,[team],offensive,0,11,13
158,New Zealand Breakers,Breakers,00:00:38.100000,52,42,10,2,3,REGULAR,0,nan. nan,1,rebound,480,479,[],offensivedeadball,0,11,14
128,New Zealand Breakers,Breakers,00:09:48,52,43,9,2,4,REGULAR,0,nan. nan,1,rebound,518,517,[team],offensive,0,13,17
84,New Zealand Breakers,Breakers,00:05:33,63,55,8,2,4,REGULAR,0,nan. nan,1,rebound,588,570,[],offensivedeadball,0,8,18
76,New Zealand Breakers,Breakers,00:04:54,68,55,13,2,4,REGULAR,0,nan. nan,1,timeout,587,,[],full,0,8,17
71,Melbourne United,United,00:04:26,68,55,13,1,4,REGULAR,0,nan. nan,1,rebound,595,593,[team],offensive,0,8,17
59,Melbourne United,United,00:03:16,71,55,16,1,4,REGULAR,0,nan. nan,1,rebound,609,607,[team],offensive,0,8,2
46,Melbourne United,United,00:02:43,74,55,19,1,4,REGULAR,0,nan. nan,1,rebound,624,623,[],offensivedeadball,0,9,19
30,Melbourne United,United,00:01:42,79,57,22,1,4,REGULAR,0,nan. nan,1,timeout,648,,[],full,0,14,19
25,New Zealand Breakers,Breakers,00:01:21,79,57,22,2,4,REGULAR,0,nan. nan,1,rebound,655,652,[team],offensive,0,14,19
16,New Zealand Breakers,Breakers,00:01:14,79,57,22,2,4,REGULAR,0,nan. nan,1,rebound,666,665,[],offensivedeadball,0,15,19
2,Melbourne United,United,00:00:07.700000,83,60,23,1,4,REGULAR,0,nan. nan,1,turnover,692,,[team],24sec,0,15,19

In [6]:
# remove NaN players
players_1 = list(pbp_df.query('tno == 1')['player'].unique())
players_2 = list(pbp_df.query('tno == 2')['player'].unique())

players_1.remove('nan. nan')
players_2.remove('nan. nan')

players = players_1
players
# pbp_df.query('tno == 2').loc[players_2.isna()]

['J. Lual-Acuil',
 'M. Dellavedova',
 'D. Barlow',
 'C. Agada',
 'C. Goulding',
 'B. Newley',
 'A. Hukporti',
 'M. Peatling',
 'S. Ili',
 'J. White',
 'D. Prewster',
 'D. Okwera',
 'C. Dalton']

Next, we extract the stint numbers of each player:

In [7]:
def get_stints_player(stints_df: pd.DataFrame, player: str):
    mask = stints_df.apply(lambda x: player in x['lineup'], axis=1)

    return stints_df.loc[mask, 'id'].to_list()

# stints1_df
players_stints = dict({})
for x in players:
    players_stints[x] = get_stints_player(stints1_df, x)

players_stints

{'J. Lual-Acuil': [1, 4, 5, 9, 10, 11, 14],
 'M. Dellavedova': [1, 5, 6, 7, 8, 9, 13],
 'D. Barlow': [1, 4, 12, 13],
 'C. Agada': [1, 2, 7, 8, 9, 11, 12, 14, 15],
 'C. Goulding': [1, 4, 5, 6, 7, 8, 9, 10, 13],
 'B. Newley': [2, 3, 10, 11, 12],
 'A. Hukporti': [2, 3, 6, 7, 8, 13],
 'M. Peatling': [2, 3, 5, 6, 7, 10, 11, 12],
 'S. Ili': [2, 3, 4, 10, 11, 12, 13],
 'J. White': [3, 4, 5, 6, 8, 9, 14, 15],
 'D. Prewster': [14, 15],
 'D. Okwera': [14, 15],
 'C. Dalton': [15]}

In [8]:
# An example: player H. Besson with/without W. McDowell-White
# for game game_id = 2031329 where Besson makes more points than on+off bc he has not been sub well
x = 'H. Besson'
y = 'W. McDowell-White'

# Mel United
x = 'J. Lual-Acuil'
y = 'M. Dellavedova'


x_stints = set(players_stints[x])
y_stints = set(players_stints[y])

print(f"Stints where {x} played:", x_stints)
print(f"Stints where {y} played:", y_stints)
print(y)

# x_shoots_df = pbp_df.query('stint1 in @x_stints and player == @x and actionType in @SHOOTS_TYPES and success == 1')
x_shoots_df = pbp_df.query('player == @x and actionType in @SHOOTS_TYPES and success == 1')
# df.query('actionType == "2pt"')

x_shoots_df

Stints where J. Lual-Acuil played: {1, 4, 5, 9, 10, 11, 14}
Stints where M. Dellavedova played: {1, 5, 6, 7, 8, 9, 13}
M. Dellavedova

,team_name,team_short_name,clock,s1,s2,lead,tno,period,periodType,pno,player,success,actionType,actionNumber,previousAction,qualifier,subType,scoring,stint1,stint2
494,Melbourne United,United,00:08:03,4,2,2,1,1,REGULAR,9,J. Lual-Acuil,1,2pt,37,,[pointsinthepaint],layup,1,1,1
475,Melbourne United,United,00:05:55,14,4,10,1,1,REGULAR,9,J. Lual-Acuil,1,2pt,62,,"[pointsinthepaint, fastbreak, fromturnover]",dunk,1,1,1
357,Melbourne United,United,00:07:13,25,18,7,1,2,REGULAR,9,J. Lual-Acuil,1,2pt,207,,[pointsinthepaint],dunk,1,5,6
275,Melbourne United,United,00:00:47.700000,32,29,3,1,2,REGULAR,9,J. Lual-Acuil,1,2pt,319,,"[2ndchance, pointsinthepaint]",layup,1,1,9
226,Melbourne United,United,00:06:37,44,33,11,1,3,REGULAR,9,J. Lual-Acuil,1,2pt,386,,[pointsinthepaint],layup,1,9,10
208,Melbourne United,United,00:04:06,49,38,11,1,3,REGULAR,9,J. Lual-Acuil,1,2pt,409,,[pointsinthepaint],dunk,1,9,11

In [9]:
players = players_1

onoff_df = pd.DataFrame()  # Correlation matrix
for x in players:
    x_stints = set(players_stints[x])
    x_pbp_df = pbp_df.query('player == @x and actionType in @SHOOTS_TYPES and success == 1')
    c_3pt = x_pbp_df.query('actionType == "3pt"').shape[0]
    c_2pt = x_pbp_df.query('actionType == "2pt"').shape[0]
    c_1pt = x_pbp_df.query('actionType == "freethrow"').shape[0]
    x_pts = 2*c_2pt + 3*c_3pt + c_1pt
    for y in players:
        if x == y:
            v = -1
        else:
            y_stints = set(players_stints[y])
            together = x_stints.intersection(y_stints)
            alone = x_stints.difference(y_stints)
            # print(x, y, together, alone)

            together_df = x_pbp_df.query('stint1 in @together')
            c_2pt = together_df.query('actionType == "2pt"').shape[0]
            c_3pt = together_df.query('actionType == "3pt"').shape[0]
            c_1pt = together_df.query('actionType == "freethrow"').shape[0]
            together_pts = 2*c_2pt + 3*c_3pt + c_1pt

            alone_df = x_pbp_df.query('stint1 in @alone')
            c_2pt = alone_df.query('actionType == "2pt"').shape[0]
            c_3pt = alone_df.query('actionType == "3pt"').shape[0]
            c_1pt = alone_df.query('actionType == "freethrow"').shape[0]
            alone_pts = 2*c_2pt + 3*c_3pt + c_1pt

            v = together_pts - alone_pts

            print(f"Player {x} ({x_pts} pts) with player {y}: {together_pts} and without: {alone_pts}")
        onoff_df.loc[x, y] = v

onoff_df

Player J. Lual-Acuil (12 pts) with player M. Dellavedova: 12 and without: 0
Player J. Lual-Acuil (12 pts) with player D. Barlow: 6 and without: 6
Player J. Lual-Acuil (12 pts) with player C. Agada: 10 and without: 2
Player J. Lual-Acuil (12 pts) with player C. Goulding: 12 and without: 0
Player J. Lual-Acuil (12 pts) with player B. Newley: 0 and without: 12
Player J. Lual-Acuil (12 pts) with player A. Hukporti: 0 and without: 12
Player J. Lual-Acuil (12 pts) with player M. Peatling: 2 and without: 10
Player J. Lual-Acuil (12 pts) with player S. Ili: 0 and without: 12
Player J. Lual-Acuil (12 pts) with player J. White: 6 and without: 6
Player J. Lual-Acuil (12 pts) with player D. Prewster: 0 and without: 12
Player J. Lual-Acuil (12 pts) with player D. Okwera: 0 and without: 12
Player J. Lual-Acuil (12 pts) with player C. Dalton: 0 and without: 12
Player M. Dellavedova (4 pts) with player J. Lual-Acuil: 2 and without: 2
Player M. Dellavedova (4 pts) with player D. Barlow: 4 and without: 0
Player M. Dellavedova (4 pts) with player C. Agada: 2 and without: 2
Player M. Dellavedova (4 pts) with player C. Goulding: 4 and without: 0
Player M. Dellavedova (4 pts) with player B. Newley: 0 and without: 4
Player M. Dellavedova (4 pts) with player A. Hukporti: 2 and without: 2
Player M. Dellavedova (4 pts) with player M. Peatling: 0 and without: 4
Player M. Dellavedova (4 pts) with player S. Ili: 2 and without: 2
Player M. Dellavedova (4 pts) with player J. White: 0 and without: 4
Player M. Dellavedova (4 pts) with player D. Prewster: 0 and without: 4
Player M. Dellavedova (4 pts) with player D. Okwera: 0 and without: 4
Player M. Dellavedova (4 pts) with player C. Dalton: 0 and without: 4
Player D. Barlow (2 pts) with player J. Lual-Acuil: 2 and without: 0
Player D. Barlow (2 pts) with player M. Dellavedova: 0 and without: 2
Player D. Barlow (2 pts) with player C. Agada: 0 and without: 2
Player D. Barlow (2 pts) with player C. Goulding: 2 and without: 0
Player D. Barlow (2 pts) with player B. Newley: 0 and without: 2
Player D. Barlow (2 pts) with player A. Hukporti: 0 and without: 2
Player D. Barlow (2 pts) with player M. Peatling: 0 and without: 2
Player D. Barlow (2 pts) with player S. Ili: 2 and without: 0
Player D. Barlow (2 pts) with player J. White: 2 and without: 0
Player D. Barlow (2 pts) with player D. Prewster: 0 and without: 2
Player D. Barlow (2 pts) with player D. Okwera: 0 and without: 2
Player D. Barlow (2 pts) with player C. Dalton: 0 and without: 2
Player C. Agada (20 pts) with player J. Lual-Acuil: 13 and without: 7
Player C. Agada (20 pts) with player M. Dellavedova: 15 and without: 5
Player C. Agada (20 pts) with player D. Barlow: 10 and without: 10
Player C. Agada (20 pts) with player C. Goulding: 15 and without: 5
Player C. Agada (20 pts) with player B. Newley: 2 and without: 18
Player C. Agada (20 pts) with player A. Hukporti: 7 and without: 13
Player C. Agada (20 pts) with player M. Peatling: 2 and without: 18
Player C. Agada (20 pts) with player S. Ili: 2 and without: 18
Player C. Agada (20 pts) with player J. White: 8 and without: 12
Player C. Agada (20 pts) with player D. Prewster: 3 and without: 17
Player C. Agada (20 pts) with player D. Okwera: 3 and without: 17
Player C. Agada (20 pts) with player C. Dalton: 0 and without: 20
Player C. Goulding (21 pts) with player J. Lual-Acuil: 12 and without: 9
Player C. Goulding (21 pts) with player M. Dellavedova: 18 and without: 3
Player C. Goulding (21 pts) with player D. Barlow: 3 and without: 18
Player C. Goulding (21 pts) with player C. Agada: 18 and without: 3
Player C. Goulding (21 pts) with player B. Newley: 3 and without: 18
Player C. Goulding (21 pts) with player A. Hukporti: 9 and without: 12
Player C. Goulding (21 pts) with player M. Peatling: 3 and without: 18
Player C. Goulding (21 pts) with player S. Ili: 3 and without: 18
Player C. Goulding (21 pts) with player J. White: 15 and without: 6
Player C. Goulding (21 pts) with player D. Prewster: 0 and without: 21
Player C. Goulding (21 pts) with player D. Okwera: 0 and without: 21
Player C. Goulding (21 pts) with player C. Dalton: 0 and without: 21
Player B. Newley (0 pts) with player J. Lual-Acuil: 0 and without: 0
Player B. Newley (0 pts) with player M. Dellavedova: 0 and without: 0
Player B. Newley (0 pts) with player D. Barlow: 0 and without: 0
Player B. Newley (0 pts) with player C. Agada: 0 and without: 0
Player B. Newley (0 pts) with player C. Goulding: 0 and without: 0
Player B. Newley (0 pts) with player A. Hukporti: 0 and without: 0
Player B. Newley (0 pts) with player M. Peatling: 0 and without: 0
Player B. Newley (0 pts) with player S. Ili: 0 and without: 0
Player B. Newley (0 pts) with player J. White: 0 and without: 0
Player B. Newley (0 pts) with player D. Prewster: 0 and without: 0
Player B. Newley (0 pts) with player D. Okwera: 0 and without: 0
Player B. Newley (0 pts) with player C. Dalton: 0 and without: 0
Player A. Hukporti (11 pts) with player J. Lual-Acuil: 0 and without: 11
Player A. Hukporti (11 pts) with player M. Dellavedova: 8 and without: 3
Player A. Hukporti (11 pts) with player D. Barlow: 6 and without: 5
Player A. Hukporti (11 pts) with player C. Agada: 2 and without: 9
Player A. Hukporti (11 pts) with player C. Goulding: 8 and without: 3
Player A. Hukporti (11 pts) with player B. Newley: 3 and without: 8
Player A. Hukporti (11 pts) with player M. Peatling: 5 and without: 6
Player A. Hukporti (11 pts) with player S. Ili: 9 and without: 2
Player A. Hukporti (11 pts) with player J. White: 3 and without: 8
Player A. Hukporti (11 pts) with player D. Prewster: 0 and without: 11
Player A. Hukporti (11 pts) with player D. Okwera: 0 and without: 11
Player A. Hukporti (11 pts) with player C. Dalton: 0 and without: 11
Player M. Peatling (0 pts) with player J. Lual-Acuil: 0 and without: 0
Player M. Peatling (0 pts) with player M. Dellavedova: 0 and without: 0
Player M. Peatling (0 pts) with player D. Barlow: 0 and without: 0
Player M. Peatling (0 pts) with player C. Agada: 0 and without: 0
Player M. Peatling (0 pts) with player C. Goulding: 0 and without: 0
Player M. Peatling (0 pts) with player B. Newley: 0 and without: 0
Player M. Peatling (0 pts) with player A. Hukporti: 0 and without: 0
Player M. Peatling (0 pts) with player S. Ili: 0 and without: 0
Player M. Peatling (0 pts) with player J. White: 0 and without: 0
Player M. Peatling (0 pts) with player D. Prewster: 0 and without: 0
Player M. Peatling (0 pts) with player D. Okwera: 0 and without: 0
Player M. Peatling (0 pts) with player C. Dalton: 0 and without: 0
Player S. Ili (5 pts) with player J. Lual-Acuil: 0 and without: 5
Player S. Ili (5 pts) with player M. Dellavedova: 3 and without: 2
Player S. Ili (5 pts) with player D. Barlow: 3 and without: 2
Player S. Ili (5 pts) with player C. Agada: 0 and without: 5
Player S. Ili (5 pts) with player C. Goulding: 3 and without: 2
Player S. Ili (5 pts) with player B. Newley: 2 and without: 3
Player S. Ili (5 pts) with player A. Hukporti: 5 and without: 0
Player S. Ili (5 pts) with player M. Peatling: 2 and without: 3
Player S. Ili (5 pts) with player J. White: 2 and without: 3
Player S. Ili (5 pts) with player D. Prewster: 0 and without: 5
Player S. Ili (5 pts) with player D. Okwera: 0 and without: 5
Player S. Ili (5 pts) with player C. Dalton: 0 and without: 5
Player J. White (6 pts) with player J. Lual-Acuil: 2 and without: 4
Player J. White (6 pts) with player M. Dellavedova: 4 and without: 2
Player J. White (6 pts) with player D. Barlow: 0 and without: 6
Player J. White (6 pts) with player C. Agada: 6 and without: 0
Player J. White (6 pts) with player C. Goulding: 4 and without: 2
Player J. White (6 pts) with player B. Newley: 0 and without: 6
Player J. White (6 pts) with player A. Hukporti: 2 and without: 4
Player J. White (6 pts) with player M. Peatling: 0 and without: 6
Player J. White (6 pts) with player S. Ili: 0 and without: 6
Player J. White (6 pts) with player D. Prewster: 2 and without: 4
Player J. White (6 pts) with player D. Okwera: 2 and without: 4
Player J. White (6 pts) with player C. Dalton: 2 and without: 4
Player D. Prewster (0 pts) with player J. Lual-Acuil: 0 and without: 0
Player D. Prewster (0 pts) with player M. Dellavedova: 0 and without: 0
Player D. Prewster (0 pts) with player D. Barlow: 0 and without: 0
Player D. Prewster (0 pts) with player C. Agada: 0 and without: 0
Player D. Prewster (0 pts) with player C. Goulding: 0 and without: 0
Player D. Prewster (0 pts) with player B. Newley: 0 and without: 0
Player D. Prewster (0 pts) with player A. Hukporti: 0 and without: 0
Player D. Prewster (0 pts) with player M. Peatling: 0 and without: 0
Player D. Prewster (0 pts) with player S. Ili: 0 and without: 0
Player D. Prewster (0 pts) with player J. White: 0 and without: 0
Player D. Prewster (0 pts) with player D. Okwera: 0 and without: 0
Player D. Prewster (0 pts) with player C. Dalton: 0 and without: 0
Player D. Okwera (0 pts) with player J. Lual-Acuil: 0 and without: 0
Player D. Okwera (0 pts) with player M. Dellavedova: 0 and without: 0
Player D. Okwera (0 pts) with player D. Barlow: 0 and without: 0
Player D. Okwera (0 pts) with player C. Agada: 0 and without: 0
Player D. Okwera (0 pts) with player C. Goulding: 0 and without: 0
Player D. Okwera (0 pts) with player B. Newley: 0 and without: 0
Player D. Okwera (0 pts) with player A. Hukporti: 0 and without: 0
Player D. Okwera (0 pts) with player M. Peatling: 0 and without: 0
Player D. Okwera (0 pts) with player S. Ili: 0 and without: 0
Player D. Okwera (0 pts) with player J. White: 0 and without: 0
Player D. Okwera (0 pts) with player D. Prewster: 0 and without: 0
Player D. Okwera (0 pts) with player C. Dalton: 0 and without: 0
Player C. Dalton (2 pts) with player J. Lual-Acuil: 0 and without: 2
Player C. Dalton (2 pts) with player M. Dellavedova: 0 and without: 2
Player C. Dalton (2 pts) with player D. Barlow: 0 and without: 2
Player C. Dalton (2 pts) with player C. Agada: 2 and without: 0
Player C. Dalton (2 pts) with player C. Goulding: 0 and without: 2
Player C. Dalton (2 pts) with player B. Newley: 0 and without: 2
Player C. Dalton (2 pts) with player A. Hukporti: 0 and without: 2
Player C. Dalton (2 pts) with player M. Peatling: 0 and without: 2
Player C. Dalton (2 pts) with player S. Ili: 0 and without: 2
Player C. Dalton (2 pts) with player J. White: 2 and without: 0
Player C. Dalton (2 pts) with player D. Prewster: 2 and without: 0
Player C. Dalton (2 pts) with player D. Okwera: 2 and without: 0

,J. Lual-Acuil,M. Dellavedova,D. Barlow,C. Agada,C. Goulding,B. Newley,A. Hukporti,M. Peatling,S. Ili,J. White,D. Prewster,D. Okwera,C. Dalton
J. Lual-Acuil,-1.0,12.0,0.0,8.0,12.0,-12.0,-12.0,-8.0,-12.0,0.0,-12.0,-12.0,-12.0
M. Dellavedova,0.0,-1.0,4.0,0.0,4.0,-4.0,0.0,-4.0,0.0,-4.0,-4.0,-4.0,-4.0
D. Barlow,2.0,-2.0,-1.0,-2.0,2.0,-2.0,-2.0,-2.0,2.0,2.0,-2.0,-2.0,-2.0
C. Agada,6.0,10.0,0.0,-1.0,10.0,-16.0,-6.0,-16.0,-16.0,-4.0,-14.0,-14.0,-20.0
C. Goulding,3.0,15.0,-15.0,15.0,-1.0,-15.0,-3.0,-15.0,-15.0,9.0,-21.0,-21.0,-21.0
B. Newley,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A. Hukporti,-11.0,5.0,1.0,-7.0,5.0,-5.0,-1.0,-1.0,7.0,-5.0,-11.0,-11.0,-11.0
M. Peatling,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0
S. Ili,-5.0,1.0,1.0,-5.0,1.0,-1.0,5.0,-1.0,-1.0,-1.0,-5.0,-5.0,-5.0
J. White,-2.0,2.0,-6.0,6.0,2.0,-6.0,-2.0,-6.0,-6.0,-1.0,-2.0,-2.0,-2.0
D. Prewster,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0
D. Okwera,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0
C. Dalton,-2.0,-2.0,-2.0,2.0,-2.0,-2.0,-2.0,-2.0,-2.0,2.0,2.0,2.0,-1.0

## ORTG and DRTG comparison

In [11]:
# Mel United
x = 'J. Lual-Acuil'
y = 'M. Dellavedova'


x_stints = set(players_stints[x])
y_stints = set(players_stints[y])

print(f"Stints where {x} played:", x_stints)
print(f"Stints where {y} played:", y_stints)

together = x_stints.intersection(y_stints)
alone = x_stints.difference(y_stints)
print(f"Stints where {x} played with {y}:", together)
print(f"Stints where {x} played without {y}:", alone)

together_df = pbp_df.query('stint1 in @together')
together_df['agg_dummy'] = 1
together_stats_df = build_stats_df(together_df, 1, "agg_dummy") # full stats for team 1
# v_together = together_stats_df['ortg']

together_stats_df

Stints where J. Lual-Acuil played: {1, 4, 5, 9, 10, 11, 14}
Stints where M. Dellavedova played: {1, 5, 6, 7, 8, 9, 13}
Stints where J. Lual-Acuil played with M. Dellavedova: {1, 5, 9}
Stints where J. Lual-Acuil played without M. Dellavedova: {10, 11, 4, 14}

/tmp/ipykernel_144662/863175587.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,tno,agg_dummy,ast,2pt_fga,2pt_fgm,2pt_fgp,patra,patrm,patrp,3pt_fga,...,drebp,orebp,trbr,opp_fga_blocked,drtg_opp,nrtg_opp,drebp_opp,orebp_opp,trbr_opp,opp_fga_blocked_opp
0,1,1,9,15,9,60.0,10,7,70.0,9,...,64.71,18.18,46.43,14.29,121.7,-25.96,81.82,35.29,53.57,0.0

In [ ]:
players = players_1

onoff_df = pd.DataFrame()  # Correlation matrix
for x in players:
    x_stints = set(players_stints[x])
    # x_pbp_df = pbp_df.query('player == @x and actionType in @SHOOTS_TYPES and success == 1')
    # c_3pt = x_pbp_df.query('actionType == "3pt"').shape[0]
    # c_2pt = x_pbp_df.query('actionType == "2pt"').shape[0]
    # c_1pt = x_pbp_df.query('actionType == "freethrow"').shape[0]
    # x_pts = 2*c_2pt + 3*c_3pt + c_1pt
    for y in players:
        if x == y:
            v = -1
        else:
            y_stints = set(players_stints[y])
            together = x_stints.intersection(y_stints)
            alone = x_stints.difference(y_stints)
            # print(x, y, together, alone)

            together_df = pbp_df.query('stint1 in @together')
            together_df['agg_dummy'] = 1
            together_stats_df = build_stats_df(together_df, 1, "agg_dummy") # full stats for team 1
            v_together = together_stats_df['ortg']

            alone_df = pbp_df.query('stint1 in @alone')
            alone_df['agg_dummy'] = 1
            alone_stats_df = build_stats_df(alone_df, 1, "agg_dummy") # full stats for team 1



            v = together_stats_df - alone_pts

            print(f"Player {x} ({x_pts} pts) with player {y}: {together_pts} and without: {alone_pts}")
        onoff_df.loc[x, y] = v

onoff_df